### PR TITLE
Add more resources and new gateway section

### PR DESCRIPTION
**Pull request by AdrianMachado**

### CODE REVIEW

**Comment by AdrianMachado** [comment]
@Kikobeats - any chance you can review?

**Comment by Kikobeats** [comment]
Hello, for merging this, first I need to read the blog posts and evaluate them; I understand you wnat to promote zuplo, but please don't rush me, I need some time for that 🙂

**Comment by cristaloleg** [comment]
Looks like a promo material rather than design or best practices.

**Comment by AdrianMachado** [comment]
I can remove the build vs buy one since that can seem like promo. The API promotion one doesn't really upsell out product at all.

**Comment by Kikobeats** [comment]
The content of the posts are pretty basic and it's covered for links already collected in this repo – Sorry I have to close this!

**Pull request closed without merging**
